inherit_gem:
  fashion_police:
    - .rubocop.yml

# Deactivate rule that makes `lambda` mandatory in defavor of `->`
# when having blocks.
Style/Lambda:
  Enabled: false

# Do not verify empty lines around blocks in specs
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - spec/**/*

# Allow using normal test doubles, since they are useful for mocking.
# See https://github.com/KissKissBankBank/fashion_police/pull/34
RSpec/VerifiedDoubles:
  Enabled: false

# Allow 5 nesting groups for context
RSpec/NestedGroups:
  Max: 5

# Enable long blocs for Gemspec files
Metrics/BlockLength:
  Exclude:
    - safe_pusher.gemspec
